version: 2
project_name: azd-ext-doctor
builds:
  - id: azd-ext-doctor
    binary: azd-ext-doctor
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: nix
    builds:
      - azd-ext-doctor
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    goos:
      - linux
  - id: windows-darwin
    builds:
      - azd-ext-doctor
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    goos:
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
